import productImage1 from './images/img2.jpg';

const productList = [
  {
    id: 1,
    name: "Zapatillas Deportivas",
    price: 59.99,
    seller: "Tienda Deportiva A",
    description: "Zapatillas cómodas para correr y hacer ejercicio.",
    image: productImage1,
  },
  {
    id: 2,
    name: "Teléfono Inteligente",
    price: 499.99,
    seller: "Electrónicos Express",
    description: "Teléfono de última generación con cámara de alta resolución.",
    image: productImage1,
  },
  {
    id: 3,
    name: "Cámara DSLR",
    price: 799.99,
    seller: "Fotografía Profesional",
    description: "Cámara profesional para capturar imágenes de alta calidad.",
    image: productImage1,
  },
  {
    id: 4,
    name: "Laptop Ultradelgada",
    price: 1299.99,
    seller: "Tecnología Avanzada",
    description: "Laptop ultradelgada con potente rendimiento.",
    image: productImage1,
  },
  {
    id: 5,
    name: "Reloj Inteligente",
    price: 149.99,
    seller: "Accesorios Tecnológicos",
    description:
      "Reloj inteligente con seguimiento de actividad y notificaciones.",
    image: productImage1,
  },
  {
    id: 6,
    name: "Bicicleta de Montaña",
    price: 499.99,
    seller: "Deportes Extremos",
    description: "Bicicleta resistente para aventuras de montaña.",
    image: productImage1,
  },
  {
    id: 7,
    name: "Libro Bestseller",
    price: 24.99,
    seller: "Librería Popular",
    description: "Último bestseller del autor reconocido.",
    image: productImage1,
  },
  {
    id: 8,
    name: "Silla Ergonómica",
    price: 89.99,
    seller: "Muebles de Oficina",
    description: "Silla ergonómica para una cómoda experiencia de trabajo.",
    image: productImage1,
  },
  {
    id: 9,
    name: "Auriculares Inalámbricos",
    price: 79.99,
    seller: "Electrónica Sonora",
    description: "Auriculares inalámbricos con cancelación de ruido.",
    image: productImage1,
  },
  {
    id: 10,
    name: "Plantas de Interior",
    price: 29.99,
    seller: "Jardín Zen",
    description: "Conjunto de plantas de interior para decorar tu hogar.",
    image: productImage1,
  },
  {
    id: 11,
    name: "Teclado Mecánico para Gaming",
    price: 129.99,
    seller: "Accesorios Gaming",
    description:
      "Teclado mecánico con retroiluminación RGB para una experiencia de juego inmersiva.",
    image: productImage1,
  },
  {
    id: 12,
    name: "Pantalones de Yoga",
    price: 34.99,
    seller: "Ropa Deportiva Zen",
    description: "Pantalones cómodos y elásticos para la práctica de yoga.",
    image: productImage1,
  },
  {
    id: 13,
    name: "Aspiradora Robot",
    price: 199.99,
    seller: "Electrodomésticos Inteligentes",
    description: "Aspiradora robot con tecnología de mapeo y control remoto.",
    image: productImage1,
  },
  {
    id: 14,
    name: "Juego de Herramientas para Jardinería",
    price: 49.99,
    seller: "Hogar y Jardín",
    description: "Herramientas duraderas para cuidar tu jardín con facilidad.",
    image: productImage1,
  },
  {
    id: 15,
    name: "Juego de Sartenes Antiadherentes",
    price: 79.99,
    seller: "Cocina Profesional",
    description:
      "Sartenes antiadherentes de alta calidad para cocinar sin complicaciones.",
    image: productImage1,
  },
  {
    id: 16,
    name: "Bolso de Cuero Vintage",
    price: 89.99,
    seller: "Moda Retro",
    description: "Bolso de cuero elegante con un toque vintage.",
    image: productImage1,
  },
  {
    id: 17,
    name: "Lámpara de Pie Moderna",
    price: 129.99,
    seller: "Iluminación Contemporánea",
    description: "Lámpara de pie con diseño moderno para iluminar tu espacio.",
    image: productImage1,
  },
  {
    id: 18,
    name: "Juego de Mesa Estratégico",
    price: 39.99,
    seller: "Juegos de Mesa Épicos",
    description:
      "Juego de mesa estratégico para pasar horas de diversión en familia.",
    image: productImage1,
  },
  {
    id: 19,
    name: "Mochila para Excursiones",
    price: 59.99,
    seller: "Aventuras al Aire Libre",
    description:
      "Mochila resistente y espaciosa para tus aventuras al aire libre.",
    image: productImage1,
  },
  {
    id: 20,
    name: "Auriculares con Cancelación de Ruido",
    price: 129.99,
    seller: "Audio de Alta Fidelidad",
    description:
      "Auriculares con tecnología de cancelación de ruido para una experiencia auditiva premium.",
    image: productImage1,
  },
];

export default productList;
